spring:
  mvc:
    static-path-pattern: /**

  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
      add-mappings: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  #
  datasource:
    url: ${DB_SERVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
